services:
  dev:
    image: node:current-alpine
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      PORT: 3000

    working_dir: /app
    volumes:
      - ../..:/app

    command: /bin/sh -c "npm install && npm run dev"
